### ISSUE TITLE
sbcl-only?

### ISSUE THREAD

**Issue by xach** [ryukinix/lisp-chat#16]
Hi, I just noticed that this project is sbcl-only. If that remains the case I'm afraid it isn't suitable for Quicklisp.

**Comment by ryukinix** [comment]
Yes, sbcl-only for now. This is just because I'm using sb-ext for threading which I choose in past just for study. I'm planning to migrate all the `sb-ext` references to a portable multi-threading library like as https://common-lisp.net/project/bordeaux-threads/

>  If that remains the case I'm afraid it isn't suitable for Quicklisp.
I understand.

Thanks for the attention and the good work at Quicklisp.

**Comment by priyadarshan** [comment]
It would be quite nice to have lisp-chat running on other versions. I am available to test it on LispWorks on Windows, Mac and Solaris.

**Comment by ryukinix** [comment]
@xach and @priyadarshan take a look in #21. Now lisp-chat has a experimental support for `sbcl`, `ccl` and `ecl` (maybe other too). 

For now only tested on Linux, macOS and Windows probably will not work fine yet the `client` because the `cl-readline` dependency. But now lisp-chat has independent systems for server and client, so if you want load just the `server` you can ignore the `cl-readline` dependency. I'll try create later a better client. `cl-readline` it's too headache: is not portable and doesn't works even inside of slime as noted #12. 

Maybe I should create a ncurses clients?

**Comment by priyadarshan** [comment]
Thank you for update. I would definitely be interested in either ncurses client or mcclim, with the first of more immediate interest. Thank you again.

**Comment by ryukinix** [comment]
> Thank you for update. I would definitely be interested in either ncurses client or mcclim, with the first of more immediate interest. Thank you again.

Thanks for the feedback. Unfortunately I cannot promise that I'll do that in soon, too many tasks in my professional job + college tasks.

But definitely I'll be glad to hear any compliant. I think before migrating to create a new client I need to fix properly #17
